from __future__ import annotations

from datetime import datetime
from typing import Optional

from fastapi import APIRouter
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel

router = APIRouter()

_COMPLEMENT = str.maketrans("ACGTacgt", "TGCAtgca")


def _rc(seq: str) -> str:
    return seq.translate(_COMPLEMENT)[::-1]


def _gc(seq: str) -> float:
    s = seq.upper()
    return round((s.count("G") + s.count("C")) / max(len(s), 1) * 100, 1)


# ── request models ────────────────────────────────────────────────────────────

class ProtocolRequest(BaseModel):
    sequence: str
    enzyme: str = "SpCas9"
    grnas: list = []
    primers: Optional[dict] = None
    cut_position: Optional[int] = None
    experiment_name: str = "Helix_Experiment"


class IdtRequest(BaseModel):
    grnas: list = []
    experiment_name: str = "Helix_Experiment"


class GenbankRequest(BaseModel):
    sequence: str
    name: str = "sequence"
    grnas: list = []
    orfs: list = []


# ── routes ────────────────────────────────────────────────────────────────────

@router.post("/export/protocol", response_class=PlainTextResponse)
def export_protocol(req: ProtocolRequest) -> str:
    date = datetime.utcnow().strftime("%Y-%m-%d")
    seq = req.sequence.upper().replace(" ", "")
    lines = []

    lines += [
        f"# CRISPR Experiment Protocol",
        f"# Generated by Helix — {date}",
        f"# Experiment: {req.experiment_name}",
        "",
        "## Target Sequence",
        f"- Length: {len(seq)} bp",
        f"- Enzyme: {req.enzyme}",
        "- PAM: NGG",
        "",
        "## Selected gRNAs (ranked by Helix ML score)",
    ]

    for i, g in enumerate(req.grnas, 1):
        guide = g.get("guide", "")[:20]
        pos = g.get("position", 0)
        score = g.get("score", 0.0)
        gc = _gc(guide)
        risk = g.get("risk", "unknown")
        lines += [
            "",
            f"### Guide {i}: {guide}",
            f"- Position: bp {pos}",
            f"- Efficiency score: {score:.4f} ({score*100:.1f}%)",
            f"- GC content: {gc}%",
            f"- Risk level: {risk}",
            f"- Predicted cut site: bp {pos + 17}",
        ]

    lines += [
        "",
        "## Reagents Required",
        "- Cas9 protein or plasmid (SpCas9 for NGG PAM)",
        "- sgRNA template (order from IDT or Addgene)",
        "- Transfection reagent (Lipofectamine 3000 recommended)",
        "- Cell line of choice",
        "- Verification primers (see below)",
        "",
        "## sgRNA Ordering Information",
    ]

    gene = req.experiment_name
    for i, g in enumerate(req.grnas[:3], 1):
        guide = g.get("guide", "")[:20]
        lines += [
            "",
            f"  IDT order format (Guide {i}):",
            f"  Name: Helix_{gene}_{i}",
            f"  Sequence: {guide}NGG",
            "  Scale: 25 nmole",
            "  Purification: Standard desalting",
        ]

    lines += [
        "",
        "## Verification Protocol",
        "1. Transfect cells with Cas9 + sgRNA",
        "2. Wait 48-72 hours",
        "3. Extract genomic DNA",
        "4. PCR amplify with verification primers",
        "5. Run Sanger sequencing or T7E1 assay",
        "6. Analyze indels with TIDE or ICE",
    ]

    if req.primers:
        fwd = req.primers.get("forward", {})
        rev = req.primers.get("reverse", {})
        lines += [
            "",
            "## Primers",
        ]
        if fwd:
            lines.append(f"  Forward: {fwd.get('sequence', '')} (Tm: {fwd.get('tm', '?')}°C)")
        if rev:
            lines.append(f"  Reverse: {rev.get('sequence', '')} (Tm: {rev.get('tm', '?')}°C)")
        size = req.primers.get("amplicon_size")
        if size:
            lines.append(f"  Amplicon: {size} bp")

    lines += [
        "",
        "## Expected Outcomes",
        "Based on Helix outcome simulation:",
        "  - NHEJ efficiency: ~85-95%",
        "  - Frameshift probability: ~65%",
        "  - Most likely indel: -1bp",
        "",
        "## Notes",
        "- Verify editing efficiency by Sanger sequencing",
        "- Consider multiple guides for redundancy",
        "- Off-target analysis recommended before experiments",
        "- Generated by Helix CRISPR Suite v0.4",
    ]

    return "\n".join(lines)


@router.post("/export/idt_order", response_class=PlainTextResponse)
def export_idt_order(req: IdtRequest) -> str:
    rows = ["Name,Sequence,Scale,Purification,Notes"]
    for i, g in enumerate(req.grnas, 1):
        guide = g.get("guide", "")[:20]
        score = g.get("score", 0.0)
        name = req.experiment_name
        rows.append(
            f"{name}_g{i}_fwd,ACCG{guide},25nm,Standard,gRNA guide score={score:.4f}"
        )
        rows.append(
            f"{name}_g{i}_rev,AAAC{_rc(guide)},25nm,Standard,gRNA reverse complement"
        )
    return "\n".join(rows)


@router.post("/export/genbank", response_class=PlainTextResponse)
def export_genbank(req: GenbankRequest) -> str:
    seq = req.sequence.upper().replace(" ", "")
    ts = datetime.utcnow().strftime("%Y%m%d%H%M%S")
    accession = f"HELIX_{ts}"
    name = req.name[:16].ljust(16)
    date_str = datetime.utcnow().strftime("%d-%b-%Y").upper()

    lines = [
        f"LOCUS       {name} {len(seq):>9} bp    DNA    linear   {date_str}",
        f"DEFINITION  {req.name} — analyzed by Helix CRISPR Suite",
        f"ACCESSION   {accession}",
        f"VERSION     {accession}.1",
        "FEATURES             Location/Qualifiers",
    ]

    for g in req.grnas:
        pos = g.get("position", 1)
        score = g.get("score", 0.0)
        guide = g.get("guide", "")[:20]
        start = max(1, pos)
        end = start + 20
        label = f"{guide[:8]}... (score={score:.2f})"
        lines += [
            f"     misc_feature    {start}..{end}",
            f'                     /label="{label}"',
            '                     /note="gRNA binding site"',
            '                     /color="#00ff88"',
        ]

    for orf in req.orfs:
        start = orf.get("start", 1)
        end = orf.get("end", 1)
        frame = orf.get("frame", 1)
        lines += [
            f"     CDS             {start}..{end}",
            f'                     /label="ORF_{frame}"',
            f'                     /note="Open reading frame, frame {frame}"',
        ]

    lines.append("ORIGIN")
    for i in range(0, len(seq), 60):
        chunk = seq[i:i + 60]
        spaced = " ".join(chunk[j:j + 10] for j in range(0, len(chunk), 10))
        lines.append(f"{i + 1:>9} {spaced}")

    lines.append("//")
    return "\n".join(lines)
